# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.background-update-timer", 1405029807);
user_pref("app.update.lastUpdateTime.user-agent-updates-timer", 1405029927);
user_pref("app.update.url.override", "https://aus4.mozilla.org/update/3/B2G/28.0/20140709000201/flame/en-US/aurora/Boot2Gecko%202.0.0.0-prerelease/default/default/update.xml?force=1");
user_pref("apz.allow-checkerboarding", true);
user_pref("apz.use_paint_duration", true);
user_pref("apz.velocity_bias", "1.0");
user_pref("apz.x_skate_size_multiplier", "1.5");
user_pref("apz.y_skate_size_multiplier", "2.5");
user_pref("browser.cache.disk.capacity", 71508);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("consoleservice.enabled", true);
user_pref("device.storage.writable.name", "sdcard");
user_pref("devtools.debugger.remote-enabled", true);
user_pref("dom.browser_frames.useAsyncPanZoom", true);
user_pref("dom.mms.requestStatusReport", false);
user_pref("dom.mms.retrieval_mode", "automatic-home");
user_pref("dom.mozApps.maxLocalId", 1029);
user_pref("dom.mozApps.used", true);
user_pref("dom.sms.requestStatusReport", false);
user_pref("gecko.buildID", "20140616171114");
user_pref("gecko.mstone", "28.0");
user_pref("idle.lastDailyNotification", 1405527647);
user_pref("intl.accept_languages", "en-US, en");
user_pref("layers.composer2d.enabled", true);
user_pref("layers.offmainthreadcomposition.log-animations", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.localDomains", "gaiamobile.org,communications.gaiamobile.org,fl.gaiamobile.org,setringtone.gaiamobile.org,wappush.gaiamobile.org,email.gaiamobile.org,clock.gaiamobile.org,ringtones.gaiamobile.org,sms.gaiamobile.org,video.gaiamobile.org,settings.gaiamobile.org,keyboard.gaiamobile.org,bluetooth.gaiamobile.org,browser.gaiamobile.org,homescreen.gaiamobile.org,pdfjs.gaiamobile.org,calendar.gaiamobile.org,costcontrol.gaiamobile.org,system.gaiamobile.org,music.gaiamobile.org,wallpaper.gaiamobile.org,camera.gaiamobile.org,fm.gaiamobile.org,gallery.gaiamobile.org,marketplace.firefox.com.gaiamobile.org");
user_pref("privacy.donottrackheader.value", -1);
user_pref("ril.mms.mmsc", "http://mmsc.mobile.att.net");
user_pref("ril.mms.mmsport", 80);
user_pref("ril.mms.mmsproxy", "proxy.mobile.att.net");
user_pref("ril.numRadioInterfaces", 2);
user_pref("ril.radio.disabled", false);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.telemetry.previousBuildID", "20140616171114");
